### ISSUE TITLE
RuntimeError freeze_support()

### ISSUE THREAD

**Issue by Jurafsky21** [yhcc/BARTABSA#10]
I'm following your readme, while using train.py in the dataset pengb I had this error:

` python train.py --dataset pengb/14lap
Read cache from caches/data_facebook/bart-base_pengb/14lap_False.pt.
The number of tokens in tokenizer  50265
50268 50273
input fields after batch(if batch size is 2):
        tgt_tokens: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2, 22])
        src_tokens: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2, 41])
        src_seq_len: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2])
        tgt_seq_len: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2])
target fields after batch(if batch size is 2):
        tgt_tokens: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2, 22])
        target_span: (1)type:numpy.ndarray (2)dtype:object, (3)shape:(2,)
        tgt_seq_len: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2])

training epochs started 2021-12-10-15-44-42-060416
Epoch 1/50:   0%|                                                          | 0/2850 [00:00<?, ?it/s, loss:{0:<6.5f}]Read cache from caches/data_facebook/bart-base_pengb/14lap_False.pt.
The number of tokens in tokenizer  50265
50268 50273
input fields after batch(if batch size is 2):
        tgt_tokens: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2, 22])
        src_tokens: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2, 41])
        src_seq_len: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2])
        tgt_seq_len: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2])
target fields after batch(if batch size is 2):
        tgt_tokens: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2, 22])
        target_span: (1)type:numpy.ndarray (2)dtype:object, (3)shape:(2,)
        tgt_seq_len: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2])

training epochs started 2021-12-10-15-44-52-779581
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sp\.conda\envs\BARTABSA\project\BARTABSA-main\peng\train.py", line 155, in <module>
    trainer.train(load_best_model=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fastNLP\core\trainer.py", line 667, in train
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\fastNLP\core\trainer.py", line 658, in train
    self._train()
  File "C:\ProgramData\Anaconda3\lib\site-packages\fastNLP\core\trainer.py", line 712, in _train
    for batch_x, batch_y in self.data_iterator:
  File "C:\ProgramData\Anaconda3\lib\site-packages\fastNLP\core\batch.py", line 266, in __iter__
    for indices, batch_x, batch_y in self.dataiter:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...`

Reading around it seems that : _multiprocessing usually doesn't work in a console in Windows. When using a spawning system instead of fork, python must import modules and create state in the child process to get things to work. The outer script must be protected with a if __name__=="__main__": clause._
I don't know where to change the code however. Any hints?

**Comment by yhcc** [comment]
Maybe just set the ``num_workers''  in Trainer to 0 will solve this problem.

**Comment by HappyBoyss** [comment]
请问您解决了吗，我也是这个错误

**Comment by HappyBoyss** [comment]
请问您解决这个问题了吗，我也是这个错误
