### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wangpeiyi9979** [yhcc/BARTABSA#4]
您好，在我按照readme和issue#1安装好相关库后。
我在训练时遇到一个错误，不知道怎么回事。
```
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    fitlog.set_log_dir('logs')
  File "miniconda3/envs/bart-absa/lib/python3.7/site-packages/fitlog/__init__.py", line 122, in set_log_dir
    _logger.set_log_dir(log_dir, new_log)
  File "miniconda3/envs/bart-absa/lib/python3.7/site-packages/fitlog/fastlog/logger.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "miniconda3/envs/bart-absa/lib/python3.7/site-packages/fitlog/fastlog/logger.py", line 174, in set_log_dir
    raise NotADirectoryError("`{}` is not exist.".format(log_dir))
NotADirectoryError: `logs` is not exist.
```

**Comment by Wangpeiyi9979** [comment]
好吧，看了源码发现要自己见一个 logs 目录 emmm
