### ISSUE TITLE
NotADirectoryError: `logs` is not exist.

### ISSUE THREAD

**Issue by Jurafsky21** [yhcc/BARTABSA#9]
Hello,
I'm following your instruction in the readme but when I try to launch

_python train.py --dataset pengb/14lap_

I get this error. What could be the cause?
```
Traceback (most recent call last):
  File ".\train.py", line 24, in <module>
    fitlog.set_log_dir('logs')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitlog\__init__.py", line 122, in set_log_dir
    _logger.set_log_dir(log_dir, new_log)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitlog\fastlog\logger.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitlog\fastlog\logger.py", line 174, in set_log_dir
    raise NotADirectoryError("`{}` is not exist.".format(log_dir))
NotADirectoryError: `logs` is not exist.
```

**Comment by Jurafsky21** [comment]
I created a logs directory where the train.py is located and it seems to work now.

**Comment by butujvzipi** [comment]
终端输入命令：
fitlog init .
即可解决
